In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_table("hospital_infct.txt")
#path

In [3]:
df.head()

ID   Stay   Age  InfctRsk  Culture   Xray  Beds  MedSchool  Region  Census  \
0   1   7.13  55.7       4.1      9.0   39.6   279          2       4     207   
1   2   8.82  58.2       1.6      3.8   51.7    80          2       2      51   
2   3   8.34  56.9       2.7      8.1   74.0   107          2       3      82   
3   4   8.95  53.7       5.6     18.9  122.8   147          2       4      53   
4   5  11.20  56.5       5.7     34.5   88.9   180          2       1     134   

   Nurses  Facilities  
0     241        60.0  
1      52        40.0  
2      54        20.0  
3     148        40.0  
4     151        40.0

In [4]:
df.columns

Index(['ID', 'Stay', 'Age', 'InfctRsk', 'Culture', 'Xray', 'Beds', 'MedSchool',
       'Region', 'Census', 'Nurses', 'Facilities'],
      dtype='object')

In [5]:
x_data=df.drop(["InfctRsk"],axis=1) #except for target the otner columns is our x data
x_data

ID   Stay   Age  Culture   Xray  Beds  MedSchool  Region  Census  \
0      1   7.13  55.7      9.0   39.6   279          2       4     207   
1      2   8.82  58.2      3.8   51.7    80          2       2      51   
2      3   8.34  56.9      8.1   74.0   107          2       3      82   
3      4   8.95  53.7     18.9  122.8   147          2       4      53   
4      5  11.20  56.5     34.5   88.9   180          2       1     134   
..   ...    ...   ...      ...    ...   ...        ...     ...     ...   
108  109  11.80  53.8      9.1  116.9   571          1       2     441   
109  110   9.50  49.3     42.0   70.9    98          2       3      68   
110  111   7.70  56.9     12.2   67.9   129          2       4      85   
111  112  17.94  56.2     26.4   91.8   835          1       1     791   
112  113   9.41  59.5     20.6   91.7    29          2       3      20   

     Nurses  Facilities  
0       241        60.0  
1        52        40.0  
2        54        20.0  
3       148        40.0  
4       151        40.0  
..      ...         ...  
108     469        62.9  
109      46        22.9  
110     136        62.9  
111     407        62.9  
112      22        22.9  

[113 rows x 11 columns]

In [6]:
y = df.InfctRsk.values #values convert into numpy array
y

array([4.1, 1.6, 2.7, 5.6, 5.7, 5.1, 4.6, 5.4, 4.3, 6.3, 4.9, 4.3, 7.7,
       3.7, 4.2, 5.5, 4.5, 6.4, 4.2, 4.1, 4.2, 4.8, 5. , 4.8, 4. , 3.9,
       4.5, 3.2, 4.4, 4.9, 5. , 5.2, 5.3, 6.1, 6.3, 5. , 2.8, 4.6, 4.1,
       1.3, 3.7, 4.7, 3. , 5.6, 5.5, 4.6, 6.5, 5.5, 1.8, 4.2, 5.6, 4.3,
       7.6, 7.8, 3.1, 3.9, 3.7, 4.3, 3.9, 4.5, 3.4, 5.7, 5.4, 4.4, 5. ,
       4.3, 4.4, 3.7, 4.5, 3.5, 4.2, 2. , 5.2, 4.5, 3.4, 4.5, 2.9, 4.9,
       4.4, 5.1, 2.9, 3.5, 5.5, 4.7, 1.7, 4.1, 2.9, 4.3, 4.8, 5.8, 2.9,
       2. , 1.3, 5.3, 5.3, 2.5, 3.8, 4.8, 2.3, 6.2, 2.6, 4.3, 2.7, 6.6,
       4.5, 2.9, 1.4, 2.1, 5.7, 5.8, 4.4, 5.9, 3.1])

In [23]:
# first of all we have to normalize the data
# x_normalized = (x - x min)/(x max -x min)
x = (x_data - np.min(x_data) / np.max(x_data) - np.min(x_data))
x = x.values


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test ,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 53)

In [25]:
x_test

array([[ 2.79911504e+01,  4.60746421e+00,  1.51112291e+01,
         1.69735537e+01,  5.62033708e+01,  2.18965269e+02,
         5.00000000e-01, -2.50000000e-01,  1.96974716e+02,
         1.74978659e+02,  3.13287500e+01],
       [ 5.49911504e+01,  4.10746421e+00,  1.71112291e+01,
         6.07355372e+00,  3.40033708e+01,  2.51965269e+02,
         5.00000000e-01, -2.50000000e-01,  1.96974716e+02,
         1.84978659e+02,  4.56287500e+01],
       [ 6.59911504e+01,  2.97746421e+00,  1.01112291e+01,
         6.67355372e+00,  5.31033708e+01,  2.35965269e+02,
         5.00000000e-01,  7.50000000e-01,  1.70974716e+02,
         1.87978659e+02,  4.28287500e+01],
       [ 8.09911504e+01,  8.97464213e-01,  1.01112291e+01,
         4.57355372e+00,  5.24033708e+01,  1.65965269e+02,
         5.00000000e-01,  7.50000000e-01,  1.18974716e+02,
         1.01978659e+02,  3.99287500e+01],
       [ 9.91150442e-01,  1.77746421e+00,  1.88112291e+01,
         2.17355372e+00,  1.18033708e+01,  5.09652695e+01,
  

In [26]:
#bind one col into the traninig set.......
b = np.ones(len(x_train)) #make all values as 1
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [27]:
x_train = np.column_stack((b,x_train)) #bind it...
x_train

array([[  1.        ,  49.99115044,   4.43746421, ..., 186.97471555,
        236.97865854,  45.62875   ],
       [  1.        , 106.99115044,   0.97746421, ...,  23.97471555,
         17.97865854,  17.12875   ],
       [  1.        ,  29.99115044,   3.98746421, ..., 249.97471555,
        320.97865854,  51.32875   ],
       ...,
       [  1.        ,  36.99115044,   0.79746421, ...,  29.97471555,
         30.97865854,  28.52875   ],
       [  1.        ,  28.99115044,   2.84746421, ...,  92.97471555,
         91.97865854,  31.32875   ],
       [  1.        ,  24.99115044,   1.23746421, ..., 392.97471555,
        421.97865854,  51.32875   ]])

In [28]:
## beta = ((X(trans) X)(inv))  (X(trans) Y)

In [29]:
temp1 = np.dot(x_train.T,x_train) #(x(transpose)) * x)
temp2 = np.dot(x_train.T,y_train) #(x(transpose)) * y)

In [30]:
#now calculate inverse of temp1
inv_temp1 =np.linalg.pinv(temp1)

In [31]:
beta =np.dot(inv_temp1,temp2)


In [32]:
#bind one col into test set
c = np.ones(len(x_test)) 
x_test.shape

(23, 11)

In [33]:
x_test =np.column_stack((c,x_test)) #bind it
print("shape of x_test= ",{x_test.shape})
print("shape of beta =", {beta.shape})

shape of x_test=  {(23, 12)}
shape of beta = {(12,)}


In [34]:
#predict result
predict = np.dot(x_test,beta)
predict

array([4.77605483, 4.1673857 , 4.21610898, 3.53970757, 3.38506754,
       4.92293814, 5.10925249, 4.2308469 , 4.88326891, 5.22928133,
       4.21647878, 4.14719766, 3.83090585, 3.6134189 , 3.12772477,
       6.14431717, 4.53742929, 4.8132291 , 4.14422063, 4.86076107,
       5.40343761, 4.47010635, 3.0890605 ])

In [35]:
#compute RSS(Regression sum of squre)
sum = 0.0
for i in range(len(y_test)):
    sum = sum + ((y_test[i] - predict[i]) * (y_test[i] - predict[i]))

RSS = sum    
#or -> RSS = np.sum((y_test - predict) * (y_test - predict))

print("RSS value =",RSS)


RSS value = 22.649364195394135


In [36]:
#computing TSS (Total sum of squre)
y_mean =np.mean(y_test)
TSS =np.sum((y_test - y_mean) * (y_test - y_mean))
print("TSS value =",TSS)

TSS value = 46.9391304347826


In [37]:
#computing r-squred value
R_SQ = 1- (RSS/TSS)

print("R-sq value =",R_SQ)

R-sq value = 0.5174737157335446
